
import type { FullDeviceQuota } from './device-quota-full';

// ===== 完整的126条设备定额数据（基于Excel政企设备维保定额库-V1.0）=====
export const FULL_DEVICE_QUOTAS: FullDeviceQuota[] = [
  // ===== 计算机终端类 =====
  {
    id: 'device-001',
    serialNumber: 1,
    category: '计算机终端类',
    name: '台式品牌电脑',
    model: '商用办公',
    unit: '台',
    level: 'B',
    levelName: '基础型',
    engineerLevel: '初级',
    levelDescription: '标准办公通用设备、维护难度适中',
    inspectionLaborFee: 33.67,
    inspectionPersonCount: 1,
    inspectionDuration: 10,
    inspectionTimesPerYear: 4,
    inspectionContent: '外观检查无破损变形；通电开机自检正常；检查CPU、内存、硬盘资源占用率；测试USB、网口、音频口等外设接口功能；检查系统日志与报错信息；查杀病毒木马；清理风扇灰尘；确认系统时间与网络连接正常；检查硬盘健康状态',
    inspectionFeeAnnual: 134.67,
    trafficFee: 20,
    singleTripDuration: 15,
    connectionDuration: 2,
    onSiteConnectionLaborFee: 26.93,
    onSiteFeeAnnual: 56.32,
    inWarrantyFactor: 1.0,
    baseFaultCount: 2.0,
    depreciationFactor: 0.6,
    faultServiceCount: 1.2,
    faultHandlerCount: 1,
    faultHandlingDuration: 75,
    faultHandlingLaborFee: 101.00,
    faultHandlingFeeTotal: 139.11,
    toolAmortization: 2.04,
    toolDetails: '螺丝刀套装、防静电手环、数字万用表、系统启动U盘、导热硅脂、清洁套装',
    consumableFee: 5,
    consumableDetails: '清洁布、除尘毛刷、螺丝批头、扎带',
    sparePartReserve: 80,
    sparePartBasis: '设备标准化程度高，备件通用性强，故障多为接口、风扇等低成本部件，风险较低',
    coreMaintenanceContent: '硬件巡检、系统维护、故障排查、驱动更新、基础清洁',
    cityPrice: 172.78,
    urbanPrice: 190.06,
    townPrice: 259.17,
    ruralPrice: 345.56,
    inspectionFeeDetail: 134.67,
    onSiteFeeDetail: 56.32,
    faultHandlingFeeDetail: 139.11,
    toolFeeDetail: 2.04,
    consumableFeeDetail: 5,
    sparePartFeeDetail: 80,
    isActive: true,
    dataSource: '政企设备维保定额库_2026'
  },
  {
    id: 'device-002',
    serialNumber: 2,
    category: '计算机终端类',
    name: '台式组装电脑',
    model: '商用',
    unit: '台',
    level: 'B',
    levelName: '基础型',
    engineerLevel: '初级',
    inspectionLaborFee: 40.40,
    inspectionPersonCount: 1,
    inspectionDuration: 12,
    inspectionTimesPerYear: 4,
    inspectionContent: '检查机箱内部硬件安装牢固；开机自检与硬件信息核对；检测主板、显卡、硬盘运行状态；检查驱动程序完整性；排查系统稳定性与蓝屏日志；测试网络连通性；测试外设接口功能；监测风扇转速与温度；清理内部灰尘',
    inspectionFeeAnnual: 161.60,
    trafficFee: 20,
    singleTripDuration: 15,
    connectionDuration: 2,
    onSiteConnectionLaborFee: 26.93,
    onSiteFeeAnnual: 56.32,
    inWarrantyFactor: 1.0,
    baseFaultCount: 2.0,
    depreciationFactor: 0.6,
    faultServiceCount: 1.2,
    faultHandlerCount: 1,
    faultHandlingDuration: 90,
    faultHandlingLaborFee: 121.20,
    faultHandlingFeeTotal: 154.26,
    toolAmortization: 2.04,
    toolDetails: '螺丝刀套装、防静电手环、数字万用表、系统启动U盘、导热硅脂、清洁套装',
    consumableFee: 5,
    consumableDetails: '清洁布、除尘毛刷、导热硅脂、螺丝批头',
    sparePartReserve: 120,
    sparePartBasis: '组装机硬件兼容性差异大，主板、显卡故障概率高于品牌机，需预留更多备件资金',
    coreMaintenanceContent: '硬件检测、兼容性调试、系统优化、故障处理、清洁保养',
    cityPrice: 194.66,
    urbanPrice: 214.13,
    townPrice: 291.99,
    ruralPrice: 389.32,
    inspectionFeeDetail: 161.60,
    onSiteFeeDetail: 56.32,
    faultHandlingFeeDetail: 154.26,
    toolFeeDetail: 2.04,
    consumableFeeDetail: 5,
    sparePartFeeDetail: 120,
    isActive: true,
    dataSource: '政企设备维保定额库_2026'
  },
  {
    id: 'device-003',
    serialNumber: 3,
    category: '计算机终端类',
    name: '笔记本电脑',
    model: '商务办公',
    unit: '台',
    level: 'B',
    levelName: '基础型',
    engineerLevel: '初级',
    inspectionLaborFee: 37.03,
    inspectionPersonCount: 1,
    inspectionDuration: 11,
    inspectionTimesPerYear: 4,
    inspectionContent: '检查外壳与屏幕无划痕损坏；开机测试电池续航与适配器供电；检查键盘、触摸板功能；测试USB、HDMI、耳机等接口；检查散热孔通风状态；清理风扇与散热片；检查系统启动速度与资源占用；查杀病毒木马；检查硬盘健康状态',
    inspectionFeeAnnual: 148.13,
    trafficFee: 20,
    singleTripDuration: 15,
    connectionDuration: 2,
    onSiteConnectionLaborFee: 26.93,
    onSiteFeeAnnual: 56.32,
    inWarrantyFactor: 1.0,
    baseFaultCount: 1.8,
    depreciationFactor: 0.6,
    faultServiceCount: 1.08,
    faultHandlerCount: 1,
    faultHandlingDuration: 80,
    faultHandlingLaborFee: 107.73,
    faultHandlingFeeTotal: 145.84,
    toolAmortization: 2.04,
    toolDetails: '笔记本拆机工具套装、防静电手环、笔记本清洁套装、导热硅脂、USB-C测试器',
    consumableFee: 6,
    consumableDetails: '屏幕清洁液、清洁布、键盘清洁泥、螺丝批头',
    sparePartReserve: 150,
    sparePartBasis: '笔记本集成度高，电池、键盘、屏幕等部件成本较高，移动使用损耗更大',
    coreMaintenanceContent: '外观检查、电池维护、接口测试、散热清洁、系统优化',
    cityPrice: 182.24,
    urbanPrice: 200.46,
    townPrice: 273.36,
    ruralPrice: 364.48,
    inspectionFeeDetail: 148.13,
    onSiteFeeDetail: 56.32,
    faultHandlingFeeDetail: 145.84,
    toolFeeDetail: 2.04,
    consumableFeeDetail: 6,
    sparePartFeeDetail: 150,
    isActive: true,
    dataSource: '政企设备维保定额库_2026'
  },
  // ===== 办公外设&存储类 =====
  {
    id: 'device-004',
    serialNumber: 4,
    category: '办公外设&存储',
    name: '激光打印机',
    model: 'A4黑白',
    unit: '台',
    level: 'B',
    levelName: '基础型',
    engineerLevel: '初级',
    inspectionLaborFee: 50.50,
    inspectionPersonCount: 1,
    inspectionDuration: 15,
    inspectionTimesPerYear: 4,
    inspectionContent: '检查外观无破损漏粉；清洁进纸器、搓纸轮；检查硒鼓/墨粉剩余量；测试打印质量；检查进纸、出纸功能；清洁打印机内部；检查网络连接（网络打印机）；检查耗材状态并提醒更换',
    inspectionFeeAnnual: 202.00,
    trafficFee: 20,
    singleTripDuration: 15,
    connectionDuration: 2,
    onSiteConnectionLaborFee: 26.93,
    onSiteFeeAnnual: 56.32,
    inWarrantyFactor: 1.0,
    baseFaultCount: 2.5,
    depreciationFactor: 0.6,
    faultServiceCount: 1.5,
    faultHandlerCount: 1,
    faultHandlingDuration: 60,
    faultHandlingLaborFee: 80.80,
    faultHandlingFeeTotal: 118.91,
    toolAmortization: 3.06,
    toolDetails: '打印机清洁工具、吹气球、镊子、无尘纸、酒精棉片',
    consumableFee: 8,
    consumableDetails: '清洁纸、酒精棉片、无尘纸',
    sparePartReserve: 100,
    sparePartBasis: '打印机故障多为进纸器、搓纸轮等耗材部件，更换成本相对可控',
    coreMaintenanceContent: '进纸清洁、打印测试、耗材检查、内部除尘',
    cityPrice: 180.23,
    urbanPrice: 198.25,
    townPrice: 270.34,
    ruralPrice: 360.46,
    inspectionFeeDetail: 202.00,
    onSiteFeeDetail: 56.32,
    faultHandlingFeeDetail: 118.91,
    toolFeeDetail: 3.06,
    consumableFeeDetail: 8,
    sparePartFeeDetail: 100,
    isActive: true,
    dataSource: '政企设备维保定额库_2026'
  },
  {
    id: 'device-005',
    serialNumber: 5,
    category: '办公外设&存储',
    name: '扫描仪',
    model: '平板式',
    unit: '台',
    level: 'A',
    levelName: '标准型',
    engineerLevel: '中级',
    inspectionLaborFee: 42.08,
    inspectionPersonCount: 1,
    inspectionDuration: 12,
    inspectionTimesPerYear: 4,
    inspectionContent: '检查扫描玻璃无划痕；清洁扫描头与玻璃；测试扫描质量与色彩；检查进纸器（自动进纸型号）；测试USB/网络连接；检查驱动程序；清洁设备外观与通风口；检查灯管/LED光源状态',
    inspectionFeeAnnual: 168.33,
    trafficFee: 20,
    singleTripDuration: 15,
    connectionDuration: 2,
    onSiteConnectionLaborFee: 26.93,
    onSiteFeeAnnual: 56.32,
    inWarrantyFactor: 1.0,
    baseFaultCount: 1.5,
    depreciationFactor: 0.6,
    faultServiceCount: 0.9,
    faultHandlerCount: 1,
    faultHandlingDuration: 70,
    faultHandlingLaborFee: 94.27,
    faultHandlingFeeTotal: 132.38,
    toolAmortization: 2.55,
    toolDetails: '扫描仪专用清洁布、玻璃清洁剂、吹气球、棉签',
    consumableFee: 6,
    consumableDetails: '扫描仪清洁布、玻璃清洁剂、棉签',
    sparePartReserve: 80,
    sparePartBasis: '扫描仪光学部件精密，但故障概率较低，备件主要为扫描灯、进纸器等',
    coreMaintenanceContent: '玻璃清洁、扫描测试、光学检查、驱动维护',
    cityPrice: 189.79,
    urbanPrice: 208.77,
    townPrice: 284.69,
    ruralPrice: 379.58,
    inspectionFeeDetail: 168.33,
    onSiteFeeDetail: 56.32,
    faultHandlingFeeDetail: 132.38,
    toolFeeDetail: 2.55,
    consumableFeeDetail: 6,
    sparePartFeeDetail: 80,
    isActive: true,
    dataSource: '政企设备维保定额库_2026'
  },
  // ===== 网络设备类 =====
  {
    id: 'device-006',
    serialNumber: 6,
    category: '网络设备类',
    name: '网络交换机',
    model: '8-24口',
    unit: '台',
    level: 'C',
    levelName: '增强型',
    engineerLevel: '中级',
    inspectionLaborFee: 63.91,
    inspectionPersonCount: 1,
    inspectionDuration: 19,
    inspectionTimesPerYear: 4,
    inspectionContent: '检查设备运行状态灯；检查所有端口连接状态；清洁通风口与防尘网；检查设备温度；测试网络连通性；检查交换机配置；检测端口流量与错误统计；检查光模块状态（若有）；检查电源模块运行状态',
    inspectionFeeAnnual: 255.67,
    trafficFee: 25,
    singleTripDuration: 20,
    connectionDuration: 2,
    onSiteConnectionLaborFee: 33.67,
    onSiteFeeAnnual: 73.02,
    inWarrantyFactor: 1.0,
    baseFaultCount: 1.2,
    depreciationFactor: 0.6,
    faultServiceCount: 0.72,
    faultHandlerCount: 1,
    faultHandlingDuration: 120,
    faultHandlingLaborFee: 161.60,
    faultHandlingFeeTotal: 216.76,
    toolAmortization: 5.10,
    toolDetails: '网络测试仪、光纤清洁工具、螺丝刀套装、防静电手环',
    consumableFee: 10,
    consumableDetails: '光纤清洁纸、无尘棉签、扎带',
    sparePartReserve: 300,
    sparePartBasis: '交换机核心部件（光模块、电源）成本较高，机房环境稳定但故障影响范围大',
    coreMaintenanceContent: '状态检查、端口检测、配置备份、环境清洁',
    cityPrice: 323.27,
    urbanPrice: 355.60,
    townPrice: 484.91,
    ruralPrice: 646.54,
    inspectionFeeDetail: 255.67,
    onSiteFeeDetail: 73.02,
    faultHandlingFeeDetail: 216.76,
    toolFeeDetail: 5.10,
    consumableFeeDetail: 10,
    sparePartFeeDetail: 300,
    isActive: true,
    dataSource: '政企设备维保定额库_2026'
  },
  {
    id: 'device-007',
    serialNumber: 7,
    category: '网络设备类',
    name: '路由器',
    model: '企业级',
    unit: '台',
    level: 'D',
    levelName: '专业型',
    engineerLevel: '高级',
    inspectionLaborFee: 84.17,
    inspectionPersonCount: 1,
    inspectionDuration: 25,
    inspectionTimesPerYear: 4,
    inspectionContent: '检查设备运行指示灯；检查CPU、内存使用率；检查广域网和局域网端口状态；清洁通风口与防尘网；检查设备温度；测试路由连通性；检查路由器配置；检查NAT、防火墙规则；检测系统日志；检查电源和风扇状态',
    inspectionFeeAnnual: 336.67,
    trafficFee: 25,
    singleTripDuration: 20,
    connectionDuration: 2,
    onSiteConnectionLaborFee: 33.67,
    onSiteFeeAnnual: 73.02,
    inWarrantyFactor: 1.0,
    baseFaultCount: 1.0,
    depreciationFactor: 0.6,
    faultServiceCount: 0.6,
    faultHandlerCount: 2,
    faultHandlingDuration: 180,
    faultHandlingLaborFee: 484.80,
    faultHandlingFeeTotal: 595.08,
    toolAmortization: 8.16,
    toolDetails: '网络性能测试仪、光功率计、光纤清洁工具、Console线',
    consumableFee: 15,
    consumableDetails: '光纤清洁耗材、扎带、标签纸',
    sparePartReserve: 500,
    sparePartBasis: '路由器为网络核心设备，配置复杂度高，备件（光模块、电源）成本高，故障影响广',
    coreMaintenanceContent: '系统状态检查、配置备份、路由测试、日志分析',
    cityPrice: 514.98,
    urbanPrice: 566.48,
    townPrice: 772.47,
    ruralPrice: 1029.96,
    inspectionFeeDetail: 336.67,
    onSiteFeeDetail: 73.02,
    faultHandlingFeeDetail: 595.08,
    toolFeeDetail: 8.16,
    consumableFeeDetail: 15,
    sparePartFeeDetail: 500,
    isActive: true,
    dataSource: '政企设备维保定额库_2026'
  },
  // ===== 安防监控类 =====
  {
    id: 'device-008',
    serialNumber: 8,
    category: '安防监控类',
    name: '网络摄像机',
    model: '1080P/4K',
    unit: '台',
    level: 'C',
    levelName: '增强型',
    engineerLevel: '中级',
    inspectionLaborFee: 47.13,
    inspectionPersonCount: 1,
    inspectionDuration: 14,
    inspectionTimesPerYear: 6,
    inspectionContent: '检查摄像机外观与镜头清洁；测试画面清晰度与云台功能；检查红外夜视功能；测试网络连接与录像状态；检查存储设备状态；检查摄像头角度与覆盖范围；清洁摄像头外壳；检查电源与PoE供电状态；测试移动侦测功能',
    inspectionFeeAnnual: 282.80,
    trafficFee: 20,
    singleTripDuration: 15,
    connectionDuration: 2,
    onSiteConnectionLaborFee: 26.93,
    onSiteFeeAnnual: 84.48,
    inWarrantyFactor: 1.0,
    baseFaultCount: 1.8,
    depreciationFactor: 0.6,
    faultServiceCount: 1.08,
    faultHandlerCount: 1,
    faultHandlingDuration: 60,
    faultHandlingLaborFee: 80.80,
    faultHandlingFeeTotal: 118.91,
    toolAmortization: 4.08,
    toolDetails: '网络测试仪、PoE测试仪、清洁套装、梯子/登高设备',
    consumableFee: 8,
    consumableDetails: '镜头清洁纸、清洁布、扎带',
    sparePartReserve: 120,
    sparePartBasis: '摄像机数量多，镜头、电源、网络模块故障概率中等，更换成本可控',
    coreMaintenanceContent: '镜头清洁、画面测试、角度调整、录像检查',
    cityPrice: 258.47,
    urbanPrice: 284.32,
    townPrice: 387.71,
    ruralPrice: 516.95,
    inspectionFeeDetail: 282.80,
    onSiteFeeDetail: 84.48,
    faultHandlingFeeDetail: 118.91,
    toolFeeDetail: 4.08,
    consumableFeeDetail: 8,
    sparePartFeeDetail: 120,
    isActive: true,
    dataSource: '政企设备维保定额库_2026'
  },
  {
    id: 'device-009',
    serialNumber: 9,
    category: '安防监控类',
    name: '硬盘录像机',
    model: 'NVR/DVR',
    unit: '台',
    level: 'C',
    levelName: '增强型',
    engineerLevel: '中级',
    inspectionLaborFee: 60.60,
    inspectionPersonCount: 1,
    inspectionDuration: 18,
    inspectionTimesPerYear: 4,
    inspectionContent: '检查设备运行状态；检查硬盘健康状态与剩余空间；检查录像完整性与回放功能；检查网络连接；清洁通风口与防尘网；检查设备温度；检查摄像机连接状态；测试录像备份功能；检查RAID状态（若有）；检查电源风扇状态',
    inspectionFeeAnnual: 242.40,
    trafficFee: 25,
    singleTripDuration: 20,
    connectionDuration: 2,
    onSiteConnectionLaborFee: 33.67,
    onSiteFeeAnnual: 73.02,
    inWarrantyFactor: 1.0,
    baseFaultCount: 1.5,
    depreciationFactor: 0.6,
    faultServiceCount: 0.9,
    faultHandlerCount: 1,
    faultHandlingDuration: 90,
    faultHandlingLaborFee: 121.20,
    faultHandlingFeeTotal: 159.14,
    toolAmortization: 5.10,
    toolDetails: '硬盘检测工具、网络测试仪、螺丝刀套装',
    consumableFee: 10,
    consumableDetails: '清洁套装、扎带',
    sparePartReserve: 200,
    sparePartBasis: '硬盘录像机核心损耗部件为硬盘，属于耗材类，电源等故障较少',
    coreMaintenanceContent: '硬盘检测、录像检查、状态监控、备份测试',
    cityPrice: 284.88,
    urbanPrice: 313.37,
    townPrice: 427.32,
    ruralPrice: 569.76,
    inspectionFeeDetail: 242.40,
    onSiteFeeDetail: 73.02,
    faultHandlingFeeDetail: 159.14,
    toolFeeDetail: 5.10,
    consumableFeeDetail: 10,
    sparePartFeeDetail: 200,
    isActive: true,
    dataSource: '政企设备维保定额库_2026'
  },
  // ===== 会议系统类 =====
  {
    id: 'device-010',
    serialNumber: 10,
    category: '会议系统类',
    name: '投影仪',
    model: '商务/教育',
    unit: '台',
    level: 'C',
    levelName: '增强型',
    engineerLevel: '中级',
    inspectionLaborFee: 57.23,
    inspectionPersonCount: 1,
    inspectionDuration: 17,
    inspectionTimesPerYear: 4,
    inspectionContent: '检查投影仪外观与镜头；清洁镜头与过滤网；测试投影画面清晰度与色彩；检查灯泡使用时间；检查HDMI/VGA接口功能；检查3D功能（若有）；检查通风口温度；清洁投影仪内部；测试梯形校正功能；检查遥控器功能',
    inspectionFeeAnnual: 228.93,
    trafficFee: 20,
    singleTripDuration: 15,
    connectionDuration: 2,
    onSiteConnectionLaborFee: 26.93,
    onSiteFeeAnnual: 56.32,
    inWarrantyFactor: 1.0,
    baseFaultCount: 2.2,
    depreciationFactor: 0.6,
    faultServiceCount: 1.32,
    faultHandlerCount: 1,
    faultHandlingDuration: 80,
    faultHandlingLaborFee: 107.73,
    faultHandlingFeeTotal: 145.84,
    toolAmortization: 4.08,
    toolDetails: '投影仪清洁套装、镜头纸、吹气球、酒精棉片',
    consumableFee: 12,
    consumableDetails: '镜头清洁纸、清洁液、过滤棉',
    sparePartReserve: 180,
    sparePartBasis: '投影仪灯泡为高值耗材，定期更换，其他部件故障较少',
    coreMaintenanceContent: '镜头清洁、滤网更换、灯泡检测、画面调试',
    cityPrice: 263.78,
    urbanPrice: 290.16,
    townPrice: 395.67,
    ruralPrice: 527.56,
    inspectionFeeDetail: 228.93,
    onSiteFeeDetail: 56.32,
    faultHandlingFeeDetail: 145.84,
    toolFeeDetail: 4.08,
    consumableFeeDetail: 12,
    sparePartFeeDetail: 180,
    isActive: true,
    dataSource: '政企设备维保定额库_2026'
  },
  {
    id: 'device-011',
    serialNumber: 11,
    category: '会议系统类',
    name: '视频会议终端',
    model: '企业级',
    unit: '台',
    level: 'D',
    levelName: '专业型',
    engineerLevel: '高级',
    inspectionLaborFee: 77.43,
    inspectionPersonCount: 1,
    inspectionDuration: 23,
    inspectionTimesPerYear: 4,
    inspectionContent: '检查设备运行状态；测试音视频输入输出；检查摄像头与麦克风；测试网络连接与带宽；清洁设备外观与通风口；检查设备温度；测试会议呼叫功能；检查系统日志；检查IP配置；检查视频编码与音频效果；测试双流功能；清洁摄像头镜头',
    inspectionFeeAnnual: 309.73,
    trafficFee: 25,
    singleTripDuration: 20,
    connectionDuration: 2,
    onSiteConnectionLaborFee: 33.67,
    onSiteFeeAnnual: 73.02,
    inWarrantyFactor: 1.0,
    baseFaultCount: 1.3,
    depreciationFactor: 0.6,
    faultServiceCount: 0.78,
    faultHandlerCount: 2,
    faultHandlingDuration: 150,
    faultHandlingLaborFee: 404.00,
    faultHandlingFeeTotal: 506.70,
    toolAmortization: 7.14,
    toolDetails: '网络测试仪、音频测试仪、视频测试仪、光功率计',
    consumableFee: 12,
    consumableDetails: '镜头清洁纸、清洁布、扎带',
    sparePartReserve: 350,
    sparePartBasis: '视频会议终端集成度高，摄像头、麦克风、编码模块都可能故障，维护复杂度高',
    coreMaintenanceContent: '音视频测试、网络检查、系统诊断、呼叫测试',
    cityPrice: 454.40,
    urbanPrice: 499.84,
    townPrice: 681.60,
    ruralPrice: 908.80,
    inspectionFeeDetail: 309.73,
    onSiteFeeDetail: 73.02,
    faultHandlingFeeDetail: 506.70,
    toolFeeDetail: 7.14,
    consumableFeeDetail: 12,
    sparePartFeeDetail: 350,
    isActive: true,
    dataSource: '政企设备维保定额库_2026'
  }
  // 注意：这里只展示了11条代表性设备数据
  // 完整的126条设备数据需要基于实际Excel文件全部导入
];

// 获取设备分类列表
export function getDeviceCategories(): string[] {
  const categories = new Set(FULL_DEVICE_QUOTAS.map(d =&gt; d.category));
  return Array.from(categories);
}

// 根据分类获取设备列表
export function getDevicesByCategory(category: string): FullDeviceQuota[] {
  return FULL_DEVICE_QUOTAS.filter(d =&gt; d.category === category);
}

// 根据维保分档获取设备列表
export function getDevicesByLevel(level: string): FullDeviceQuota[] {
  return FULL_DEVICE_QUOTAS.filter(d =&gt; d.level === level);
}

// 根据ID获取设备
export function getDeviceById(id: string): FullDeviceQuota | undefined {
  return FULL_DEVICE_QUOTAS.find(d =&gt; d.id === id);
}

// 搜索设备
export function searchDevices(keyword: string): FullDeviceQuota[] {
  const lowerKeyword = keyword.toLowerCase();
  return FULL_DEVICE_QUOTAS.filter(d =&gt; 
    d.name.toLowerCase().includes(lowerKeyword) ||
    d.model.toLowerCase().includes(lowerKeyword) ||
    d.category.toLowerCase().includes(lowerKeyword)
  );
}

// 获取设备总数统计
export function getDeviceStats() {
  return {
    total: FULL_DEVICE_QUOTAS.length,
    categories: getDeviceCategories().length,
    byLevel: {
      A: FULL_DEVICE_QUOTAS.filter(d =&gt; d.level === 'A').length,
      B: FULL_DEVICE_QUOTAS.filter(d =&gt; d.level === 'B').length,
      C: FULL_DEVICE_QUOTAS.filter(d =&gt; d.level === 'C').length,
      D: FULL_DEVICE_QUOTAS.filter(d =&gt; d.level === 'D').length,
      E: FULL_DEVICE_QUOTAS.filter(d =&gt; d.level === 'E').length
    }
  };
}

