CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  name text,
  role text NOT NULL DEFAULT 'its_member',
  is_active boolean NOT NULL DEFAULT true,
  phone text,
  email text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text
);

CREATE TABLE IF NOT EXISTS auth_sessions (
  token_hash text PRIMARY KEY,
  role text NOT NULL,
  user_id bigint REFERENCES users(id) ON DELETE CASCADE,
  username text,
  name text,
  expires_at bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS clients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_code text NOT NULL UNIQUE,
  name text NOT NULL,
  contact_person text,
  contact_phone text,
  contact_email text,
  address text,
  region text DEFAULT '城区',
  level text DEFAULT 'normal',
  remark text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS device_quotas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL,
  name text NOT NULL,
  brand text,
  model text,
  specification text,
  maintenance_tier text DEFAULT 'C档',
  level text DEFAULT 'B',
  engineer_level text DEFAULT '初级',
  annual_fault_count double precision DEFAULT 0,
  annual_failure_count double precision DEFAULT 0,
  year_fault_rate double precision DEFAULT 0,
  a_gear_fault_count double precision DEFAULT 0,
  b_gear_fault_count double precision DEFAULT 0,
  c_gear_fault_count double precision DEFAULT 0,
  d_gear_fault_count double precision DEFAULT 0,
  e_gear_fault_count double precision DEFAULT 0,
  fault_processing_days double precision DEFAULT 0,
  inspection_days double precision DEFAULT 0,
  on_site_count integer DEFAULT 0,
  inspection_labor_fee numeric(18,2) DEFAULT 0,
  inspection_person_count integer DEFAULT 1,
  inspection_duration double precision DEFAULT 0,
  inspection_times_per_year integer DEFAULT 4,
  inspection_content text,
  visit_service_fee numeric(18,2) DEFAULT 0,
  visit_person_count integer DEFAULT 1,
  visit_duration double precision DEFAULT 0,
  visit_frequency double precision DEFAULT 0,
  traffic_fee numeric(18,2) DEFAULT 0,
  single_trip_duration double precision DEFAULT 0,
  connection_duration double precision DEFAULT 0,
  on_site_connection_labor_fee numeric(18,2) DEFAULT 0,
  in_warranty_factor double precision DEFAULT 1.0,
  base_fault_count double precision DEFAULT 0,
  depreciation_factor double precision DEFAULT 1.0,
  fault_service_count double precision DEFAULT 0,
  fault_handler_count integer DEFAULT 1,
  fault_handling_duration double precision DEFAULT 0,
  fault_handling_fee numeric(18,2) DEFAULT 0,
  fault_handling_labor_fee numeric(18,2) DEFAULT 0,
  fault_handling_material_fee numeric(18,2) DEFAULT 0,
  tool_amortization numeric(18,2) DEFAULT 0,
  tool_details text,
  consumable_fee numeric(18,2) DEFAULT 0,
  consumable_details text,
  spare_part_reserve numeric(18,2) DEFAULT 0,
  spare_part_fee numeric(18,2) DEFAULT 0,
  spare_part_basis text,
  city_price numeric(18,2) DEFAULT 0,
  fault_handling_fee_total numeric(18,2) DEFAULT 0,
  core_maintenance_content text,
  sort_order integer DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  unit text DEFAULT '台',
  year1_total_price numeric(18,2) DEFAULT 0,
  year2_total_price numeric(18,2) DEFAULT 0,
  year3_total_price numeric(18,2) DEFAULT 0,
  urban_price numeric(18,2) DEFAULT 0,
  town_price numeric(18,2) DEFAULT 0,
  rural_price numeric(18,2) DEFAULT 0,
  fault_handling_fee_detail text,
  note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS engineering_quotes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_number text NOT NULL UNIQUE,
  version integer DEFAULT 1,
  project_name text NOT NULL,
  client_id bigint REFERENCES clients(id) ON DELETE SET NULL,
  client_name text,
  contact_person text,
  contact_phone text,
  contact_email text,
  project_address text,
  construction_area double precision DEFAULT 0,
  quote_date date,
  validity_days integer DEFAULT 30,
  engineer_name text,
  subtotal numeric(18,2) DEFAULT 0,
  management_rate double precision DEFAULT 0.08,
  management_fee numeric(18,2) DEFAULT 0,
  profit_rate double precision DEFAULT 0.10,
  profit numeric(18,2) DEFAULT 0,
  regulatory_rate double precision DEFAULT 0.01,
  regulatory_fee numeric(18,2) DEFAULT 0,
  tax_rate double precision DEFAULT 0.13,
  tax numeric(18,2) DEFAULT 0,
  total numeric(18,2) DEFAULT 0,
  status text DEFAULT 'draft',
  items jsonb,
  created_by text,
  created_by_name text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS maintenance_quotes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_number text NOT NULL UNIQUE,
  version integer DEFAULT 1,
  project_name text NOT NULL,
  client_id bigint REFERENCES clients(id) ON DELETE SET NULL,
  client_name text,
  contact_person text,
  contact_phone text,
  contact_email text,
  project_address text,
  quote_date date,
  validity_days integer DEFAULT 30,
  engineer_name text,
  engineer_level text DEFAULT '中级',
  sla_coefficient double precision DEFAULT 1.0,
  region_coefficient double precision DEFAULT 1.0,
  years integer DEFAULT 1,
  years_discount double precision DEFAULT 1.0,
  equipment_count integer DEFAULT 0,
  bulk_discount double precision DEFAULT 1.0,
  total_inspection numeric(18,2) DEFAULT 0,
  total_onsite numeric(18,2) DEFAULT 0,
  total_repair numeric(18,2) DEFAULT 0,
  total_tools numeric(18,2) DEFAULT 0,
  total_consumables numeric(18,2) DEFAULT 0,
  total_spare_parts numeric(18,2) DEFAULT 0,
  subtotal_before_discount numeric(18,2) DEFAULT 0,
  sla_adjustment numeric(18,2) DEFAULT 0,
  region_adjustment numeric(18,2) DEFAULT 0,
  subtotal_after_coefficients numeric(18,2) DEFAULT 0,
  years_discount_amount numeric(18,2) DEFAULT 0,
  bulk_discount_amount numeric(18,2) DEFAULT 0,
  subtotal numeric(18,2) DEFAULT 0,
  tax numeric(18,2) DEFAULT 0,
  total numeric(18,2) DEFAULT 0,
  devices jsonb,
  status text DEFAULT 'draft',
  created_by text,
  created_by_name text,
  region text DEFAULT '城区',
  service_years integer DEFAULT 1,
  sla_config jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS quote_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id bigint NOT NULL,
  quote_type text NOT NULL,
  version integer NOT NULL,
  data jsonb NOT NULL,
  change_summary text,
  created_by text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS quote_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id bigint NOT NULL,
  quote_type text NOT NULL,
  action text NOT NULL,
  from_status text,
  to_status text,
  comment text,
  operator text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS quote_shares (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token text NOT NULL UNIQUE,
  quote_id bigint NOT NULL,
  quote_type text NOT NULL,
  password text,
  expires_at timestamptz,
  max_views integer DEFAULT 0,
  view_count integer DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  remark text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS self_construction_quotas (
  id text PRIMARY KEY,
  item_id text,
  category text NOT NULL,
  name text NOT NULL,
  unit text NOT NULL,
  quantity double precision DEFAULT 1,
  price numeric(18,2) NOT NULL,
  remark text,
  sort_order integer DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS intelligent_project_quotas (
  id text PRIMARY KEY,
  item_id text NOT NULL,
  serial_number integer,
  category text NOT NULL,
  name text NOT NULL,
  brand_model text DEFAULT '',
  description text,
  deductible_tax_rate double precision DEFAULT 0,
  unit text NOT NULL,
  price numeric(18,2) NOT NULL,
  remark text,
  sort_order integer DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS labor_price_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level text NOT NULL,
  unit_price numeric(18,2) NOT NULL,
  unit text DEFAULT '人天',
  description text DEFAULT '',
  sort_order integer DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS maintenance_device_quotas (
  id text PRIMARY KEY,
  category text NOT NULL,
  name text NOT NULL,
  brand text DEFAULT '',
  model text DEFAULT '',
  specification text DEFAULT '',
  unit text DEFAULT '台',
  quantity double precision DEFAULT 1,
  original_price numeric(18,2) DEFAULT 0,
  maintenance_rate double precision DEFAULT 0,
  annual_fee numeric(18,2) DEFAULT 0,
  network_type text DEFAULT '内网',
  remark text,
  sort_order integer DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS maintenance_rate_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_type text NOT NULL,
  rate double precision NOT NULL DEFAULT 0,
  maintenance_rate double precision DEFAULT 0,
  description text DEFAULT '',
  sort_order integer DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sla_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level_name text NOT NULL DEFAULT '',
  sla_level text,
  inspection_frequency text DEFAULT '',
  response_time text DEFAULT '',
  resolution_time text DEFAULT '',
  fix_time text DEFAULT '',
  on_site_time text DEFAULT '',
  penalty_rate double precision DEFAULT 0,
  description text DEFAULT '',
  sort_order integer DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS quotation_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  client_name text NOT NULL,
  client_region text,
  project_name text,
  quote_type text DEFAULT 'full',
  total_amount numeric(18,2) DEFAULT 0,
  device_count integer DEFAULT 0,
  quote_data jsonb,
  status text DEFAULT 'draft',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS quotation_devices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quotation_id bigint NOT NULL REFERENCES quotation_records(id) ON DELETE CASCADE,
  device_name text NOT NULL,
  brand text,
  model text,
  category text,
  quantity integer DEFAULT 1,
  unit_price numeric(18,2) DEFAULT 0,
  total_price numeric(18,2) DEFAULT 0,
  maintenance_rate double precision DEFAULT 0,
  maintenance_fee numeric(18,2) DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS agent_configs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  description text,
  system_prompt text NOT NULL,
  model text DEFAULT 'default',
  temperature double precision DEFAULT 0.7,
  enabled boolean NOT NULL DEFAULT true,
  created_by bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS agent_skills (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id bigint NOT NULL REFERENCES agent_configs(id) ON DELETE CASCADE,
  skill_name text NOT NULL,
  skill_type text NOT NULL,
  config_json jsonb,
  enabled boolean NOT NULL DEFAULT true,
  priority integer DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS agent_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id text NOT NULL UNIQUE,
  user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  user_name text,
  agent_id bigint REFERENCES agent_configs(id) ON DELETE SET NULL,
  agent_name text,
  title text DEFAULT '新对话',
  last_message text DEFAULT '',
  message_count integer DEFAULT 0,
  last_message_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  is_deleted boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS agent_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  agent_id bigint REFERENCES agent_configs(id) ON DELETE SET NULL,
  session_id text REFERENCES agent_sessions(session_id) ON DELETE CASCADE,
  user_message text NOT NULL,
  agent_response text NOT NULL,
  actions_executed jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS agent_knowledge_base (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id bigint REFERENCES agent_configs(id) ON DELETE CASCADE,
  title text NOT NULL,
  content text NOT NULL,
  category text,
  tags text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ai_model_configs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  provider text NOT NULL,
  model_name text NOT NULL,
  api_endpoint text NOT NULL,
  api_key text NOT NULL,
  temperature double precision DEFAULT 0.7,
  max_tokens integer DEFAULT 4000,
  system_prompt text,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  is_default boolean NOT NULL DEFAULT false,
  sort_order integer DEFAULT 0,
  created_by text,
  display_name text,
  base_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ai_model_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_id bigint REFERENCES ai_model_configs(id) ON DELETE SET NULL,
  provider text NOT NULL,
  model_name text NOT NULL,
  request_type text NOT NULL,
  prompt_length integer,
  response_length integer,
  status text NOT NULL,
  duration_ms integer,
  error_message text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ai_learning_memory (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id bigint REFERENCES clients(id) ON DELETE SET NULL,
  client_name text,
  device_signature text NOT NULL,
  device_name text,
  device_type text,
  use_years integer,
  unit_price numeric(18,2),
  quantity integer,
  raw_data jsonb,
  device_config jsonb,
  usage_count integer NOT NULL DEFAULT 1,
  last_used_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ai_feedback (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  original_text text NOT NULL,
  ai_result jsonb NOT NULL,
  corrected_result jsonb,
  feedback_type text NOT NULL,
  feedback_comment text,
  client_name text,
  operator text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS quote_device_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id bigint REFERENCES clients(id) ON DELETE SET NULL,
  client_name text,
  device_signature text NOT NULL,
  device_data jsonb,
  quote_total numeric(18,2),
  quote_id bigint,
  quote_type text,
  created_at timestamptz NOT NULL DEFAULT now()
);
