-- 报价资料库：管理端上传、维护，用户端只读浏览
-- 主要承载项目简述 + 报价单（基于康海物流固话线路整改报价V2.xlsx 模板）
-- 以及现场查勘照片 / 其他资料（CAD、方案、建议书等）

CREATE TABLE IF NOT EXISTS quote_library (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  title text NOT NULL,
  client_name text,
  project_name text,
  project_description text NOT NULL,
  quote_data jsonb NOT NULL,
  total_amount numeric(18,2) NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'CNY',
  is_published boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_quote_library_user_id ON quote_library(user_id);
CREATE INDEX IF NOT EXISTS idx_quote_library_created_at ON quote_library(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_quote_library_client ON quote_library(client_name);
CREATE INDEX IF NOT EXISTS idx_quote_library_project ON quote_library(project_name);

-- 报价资料库附件（现场照片、其他资料）
CREATE TABLE IF NOT EXISTS quote_library_attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  library_id bigint NOT NULL REFERENCES quote_library(id) ON DELETE CASCADE,
  category text NOT NULL CHECK (category IN ('survey_photo', 'other')),
  original_name text NOT NULL,
  stored_path text NOT NULL,
  mime_type text,
  file_size bigint,
  uploaded_by bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_qla_library ON quote_library_attachments(library_id);
CREATE INDEX IF NOT EXISTS idx_qla_category ON quote_library_attachments(category);

-- updated_at 由应用层在 UPDATE 时显式写入，避免依赖未定义的触发器函数