-- 设备清单导入记录（成员提交、管理员审核）
CREATE TABLE IF NOT EXISTS device_imports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL,
  name text NOT NULL,
  model text NOT NULL DEFAULT '',
  level text NOT NULL DEFAULT 'B',
  engineer_level text NOT NULL DEFAULT '初级',
  device_count integer NOT NULL DEFAULT 1,
  need_spare_part boolean NOT NULL DEFAULT false,
  contract_years integer NOT NULL DEFAULT 1,
  device_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'pending',
  submitted_by text NOT NULL DEFAULT '',
  submitted_at timestamptz NOT NULL DEFAULT now(),
  reviewed_by text,
  reviewed_at timestamptz,
  review_comment text
);

CREATE INDEX IF NOT EXISTS idx_device_imports_status ON device_imports(status);
CREATE INDEX IF NOT EXISTS idx_device_imports_submitted_at ON device_imports(submitted_at DESC);
