-- 系统参数（费率/利润率/税率/维保参数等，可配置持久化）
CREATE TABLE IF NOT EXISTS system_parameters (
  key text PRIMARY KEY,
  value text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- 勘察上传记录（保存查勘问询解析结果与生成的报价）
CREATE TABLE IF NOT EXISTS survey_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  survey_data jsonb NOT NULL,
  quote_result jsonb,
  contract_years integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now()
);
