-- 未入库设备补录请求（成员报价时提交，管理员审核批准后落库 device_quotas）
CREATE TABLE IF NOT EXISTS device_suggestions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source text NOT NULL DEFAULT 'engineering',          -- 'engineering' | 'maintenance'
  quote_id text NOT NULL DEFAULT '',
  quote_number text NOT NULL DEFAULT '',
  project_name text NOT NULL DEFAULT '',
  category text NOT NULL DEFAULT '',
  name text NOT NULL,
  brand text NOT NULL DEFAULT '',
  model text NOT NULL DEFAULT '',
  specification text NOT NULL DEFAULT '',
  maintenance_tier text NOT NULL DEFAULT 'C档',
  level text NOT NULL DEFAULT 'B',
  engineer_level text NOT NULL DEFAULT '初级',
  temp_unit_price numeric(18,2) NOT NULL DEFAULT 0,
  quantity integer NOT NULL DEFAULT 1,
  location text NOT NULL DEFAULT '',
  comment text NOT NULL DEFAULT '',
  price_data jsonb NOT NULL DEFAULT '{}'::jsonb,        -- 审批时填写的价格体系
  status text NOT NULL DEFAULT 'pending',               -- pending | approved | rejected
  submitted_by text NOT NULL DEFAULT '',
  submitted_at timestamptz NOT NULL DEFAULT now(),
  reviewed_by text,
  reviewed_at timestamptz,
  review_comment text
);

CREATE INDEX IF NOT EXISTS idx_device_suggestions_status ON device_suggestions(status);
CREATE INDEX IF NOT EXISTS idx_device_suggestions_submitted_by ON device_suggestions(submitted_by);
CREATE INDEX IF NOT EXISTS idx_device_suggestions_submitted_at ON device_suggestions(submitted_at DESC);
