import { loadPostgresMigrations } from '../../../src/lib/database/postgres-migrations';

export interface TargetColumnContract {
  tableName: string;
  columnName: string;
  udtName: string;
  nullable: boolean;
  identity: boolean;
  identityGeneration: string | null;
  defaultExpression: string | null;
  numericPrecision: number | null;
  numericScale: number | null;
}

export interface TargetConstraintContract {
  tableName: string;
  constraintType: 'PRIMARY KEY' | 'UNIQUE' | 'FOREIGN KEY';
  columnName: string;
  foreignTableName: string | null;
  foreignColumnName: string | null;
  deleteRule: string | null;
}

export interface TargetIndexContract {
  tableName: string;
  indexName: string;
  unique: boolean;
  keyDefinitions: string[];
}

export interface TargetSchemaContract {
  columns: TargetColumnContract[];
  constraints: TargetConstraintContract[];
  indexes: TargetIndexContract[];
}

export interface TargetColumnMetadata {
  [key: string]: unknown;
  table_name: string;
  column_name: string;
  udt_name: string;
  is_nullable: string;
  is_identity: string;
  identity_generation: string | null;
  column_default: string | null;
  numeric_precision: number | null;
  numeric_scale: number | null;
}

export interface TargetConstraintMetadata {
  [key: string]: unknown;
  table_name: string;
  constraint_type: string;
  column_name: string;
  foreign_table_name: string | null;
  foreign_column_name: string | null;
  delete_rule: string | null;
}

export interface TargetIndexMetadata {
  [key: string]: unknown;
  table_name: string;
  index_name: string;
  is_unique: boolean;
  key_definitions: string;
}

const TYPE_UDT: Readonly<Record<string, string>> = {
  bigint: 'int8',
  text: 'text',
  boolean: 'bool',
  'double precision': 'float8',
  integer: 'int4',
  timestamptz: 'timestamptz',
  date: 'date',
  jsonb: 'jsonb',
  numeric: 'numeric',
};

function normalizeDefault(value: string | null): string | null {
  if (value === null) return null;
  let normalized = value.trim()
    .replace(/::(?:text|character varying|double precision|numeric|integer|bigint|boolean)/gi, '')
    .replace(/^\(([\s\S]*)\)$/, '$1')
    .replace(/\s+/g, ' ')
    .toLowerCase();
  if (/^[+-]?\d+(?:\.\d+)?$/.test(normalized)) {
    normalized = String(Number(normalized));
  }
  return normalized;
}

function parseColumn(
  tableName: string,
  columnName: string,
  definition: string,
): TargetColumnContract {
  // 去掉行内 -- 注释、尾部分号和逗号，避免被误当默认值
  const clean = definition.replace(/--[\s\S]*$/, '').replace(/[;,]\s*$/, '').trim();
  const typeMatch = /^(bigint|text|boolean|double precision|integer|timestamptz|date|jsonb|numeric)(?:\((\d+),(\d+)\))?/i.exec(clean);
  if (!typeMatch) throw new Error(`Unsupported canonical PostgreSQL type for ${tableName}.${columnName}.`);
  const typeName = typeMatch[1].toLowerCase();
  // 排除 GENERATED BY DEFAULT AS IDENTITY 里的 DEFAULT，避免把 AS IDENTITY 误当默认值
  const defaultMatch = /(?<!GENERATED BY )\bDEFAULT\s+(.+?)(?=\s+(?:NOT NULL|PRIMARY KEY|UNIQUE|REFERENCES)\b|$)/i.exec(clean);
  const identity = /\bGENERATED BY DEFAULT AS IDENTITY\b/i.test(clean);
  return {
    tableName,
    columnName,
    udtName: TYPE_UDT[typeName],
    nullable: !/\bNOT NULL\b|\bPRIMARY KEY\b/i.test(clean),
    identity,
    identityGeneration: identity ? 'BY DEFAULT' : null,
    defaultExpression: normalizeDefault(defaultMatch?.[1] ?? null),
    numericPrecision: typeName === 'numeric' ? Number(typeMatch[2]) : null,
    numericScale: typeName === 'numeric' ? Number(typeMatch[3]) : null,
  };
}

function parseConstraint(
  tableName: string,
  columnName: string,
  definition: string,
): TargetConstraintContract[] {
  const constraints: TargetConstraintContract[] = [];
  if (/\bPRIMARY KEY\b/i.test(definition)) {
    constraints.push({
      tableName,
      constraintType: 'PRIMARY KEY',
      columnName,
      foreignTableName: null,
      foreignColumnName: null,
      deleteRule: null,
    });
  }
  if (/\bUNIQUE\b/i.test(definition)) {
    constraints.push({
      tableName,
      constraintType: 'UNIQUE',
      columnName,
      foreignTableName: null,
      foreignColumnName: null,
      deleteRule: null,
    });
  }
  const reference = /\bREFERENCES\s+(\w+)\((\w+)\)(?:\s+ON DELETE\s+(CASCADE|RESTRICT|SET NULL|NO ACTION))?/i.exec(definition);
  if (reference) {
    constraints.push({
      tableName,
      constraintType: 'FOREIGN KEY',
      columnName,
      foreignTableName: reference[1],
      foreignColumnName: reference[2],
      deleteRule: (reference[3] ?? 'NO ACTION').toUpperCase(),
    });
  }
  return constraints;
}

export function parseTargetSchemaContract(sql: string): TargetSchemaContract {
  const columns: TargetColumnContract[] = [];
  const constraints: TargetConstraintContract[] = [];
  const tablePattern = /CREATE TABLE IF NOT EXISTS\s+(\w+)\s*\(([\s\S]*?)\n\);/g;
  for (const tableMatch of sql.matchAll(tablePattern)) {
    const tableName = tableMatch[1];
    const seen = new Set<string>();
    for (const line of tableMatch[2].split('\n')) {
      const match = /^\s{2}(\w+)\s+(.+?)(?:,)?$/.exec(line);
      if (!match) continue;
      const columnName = match[1];
      const definition = match[2].replace(/,$/, '').trim();
      if (seen.has(columnName)) throw new Error(`Duplicate canonical PostgreSQL column ${tableName}.${columnName}.`);
      seen.add(columnName);
      columns.push(parseColumn(tableName, columnName, definition));
      constraints.push(...parseConstraint(tableName, columnName, definition));
    }
  }
  return { columns, constraints, indexes: [] };
}

function normalizeIndexKeyDefinition(value: string): string {
  return value
    .trim()
    .replaceAll('"', '')
    .replace(/\s+(?:asc|desc)\s*$/i, '')
    .replace(/\s+/g, ' ')
    .toLowerCase();
}

function parseTargetIndexContracts(sql: string): TargetIndexContract[] {
  const indexes: TargetIndexContract[] = [];
  const pattern = /CREATE\s+(UNIQUE\s+)?INDEX\s+IF\s+NOT\s+EXISTS\s+(\w+)\s+ON\s+(\w+)\s*\(([^;]+)\)\s*;/gi;
  for (const match of sql.matchAll(pattern)) {
    indexes.push({
      tableName: match[3],
      indexName: match[2],
      unique: Boolean(match[1]),
      keyDefinitions: match[4].split(',').map(normalizeIndexKeyDefinition),
    });
  }
  return indexes;
}

export function loadCanonicalTargetSchemaContract(): TargetSchemaContract {
  const migrations = loadPostgresMigrations();
  const initial = migrations.find(({ version }) => version === 1);
  const indexMigration = migrations.find(({ version }) => version === 2);
  if (!initial) throw new Error('Canonical PostgreSQL schema migration is unavailable.');
  if (!indexMigration) throw new Error('Canonical PostgreSQL index migration is unavailable.');

  const contract: TargetSchemaContract = { columns: [], constraints: [], indexes: [] };
  for (const migration of migrations) {
    const parsed = parseTargetSchemaContract(migration.sql);
    contract.columns.push(...parsed.columns);
    contract.constraints.push(...parsed.constraints);
    contract.indexes.push(...parseTargetIndexContracts(migration.sql));
    parseAlterTableColumns(migration.sql).forEach((column) => contract.columns.push(column));
  }
  if (contract.indexes.length === 0) {
    throw new Error('Canonical PostgreSQL index migration contains no indexes.');
  }
  return contract;
}

// 解析增量迁移里的 ALTER TABLE ... ADD COLUMN，补齐增量列（如 008 的 crcc_*）
function parseAlterTableColumns(sql: string): TargetColumnContract[] {
  const columns: TargetColumnContract[] = [];
  let currentTable: string | null = null;
  for (const line of sql.split('\n')) {
    const alterMatch = /ALTER\s+TABLE\s+(\w+)/i.exec(line.trim());
    if (alterMatch) {
      currentTable = alterMatch[1];
      continue;
    }
    if (!currentTable) continue;
    const addMatch = /ADD\s+COLUMN\s+(?:IF\s+NOT\s+EXISTS\s+)?(\w+)\s+([a-zA-Z0-9_.,()'"\s;]+?)(?:,)?\s*$/.exec(line.trim());
    if (!addMatch) continue;
    try {
      columns.push(parseColumn(currentTable, addMatch[1], addMatch[2].trim()));
    } catch {
      // 无法识别的 ALTER 列跳过（如带表达式默认值），避免契约解析崩溃
    }
  }
  return columns;
}

function columnFingerprint(column: TargetColumnContract): string {
  return JSON.stringify([
    column.tableName,
    column.columnName,
    column.udtName,
    column.nullable,
    column.identity,
    column.identityGeneration,
    normalizeDefault(column.defaultExpression),
    column.numericPrecision,
    column.numericScale,
  ]);
}

function metadataColumnContract(column: TargetColumnMetadata): TargetColumnContract {
  return {
    tableName: column.table_name,
    columnName: column.column_name,
    udtName: column.udt_name,
    nullable: column.is_nullable === 'YES',
    identity: column.is_identity === 'YES',
    identityGeneration: column.identity_generation,
    defaultExpression: normalizeDefault(column.column_default),
    numericPrecision: column.udt_name === 'numeric' ? Number(column.numeric_precision) : null,
    numericScale: column.udt_name === 'numeric' ? Number(column.numeric_scale) : null,
  };
}

function constraintFingerprint(constraint: TargetConstraintContract): string {
  return JSON.stringify([
    constraint.tableName,
    constraint.constraintType,
    constraint.columnName,
    constraint.foreignTableName,
    constraint.foreignColumnName,
    constraint.deleteRule,
  ]);
}

function indexFingerprint(index: TargetIndexContract): string {
  return JSON.stringify([
    index.tableName,
    index.indexName,
    index.unique,
    index.keyDefinitions.map(normalizeIndexKeyDefinition),
  ]);
}

function metadataIndexContract(index: TargetIndexMetadata): TargetIndexContract {
  return {
    tableName: index.table_name,
    indexName: index.index_name,
    unique: index.is_unique,
    keyDefinitions: index.key_definitions.split(',').map(normalizeIndexKeyDefinition),
  };
}

export function assertTargetSchemaContract(
  expected: TargetSchemaContract,
  actualColumns: readonly TargetColumnMetadata[],
  actualConstraints: readonly TargetConstraintMetadata[],
  includedTables: ReadonlySet<string>,
  actualIndexes: readonly TargetIndexMetadata[],
): void {
  const expectedColumns = expected.columns.filter(({ tableName }) => includedTables.has(tableName));
  const filteredActualColumns = actualColumns.filter(({ table_name }) => includedTables.has(table_name));
  const expectedColumnSet = new Set(expectedColumns.map(columnFingerprint));
  const actualColumnSet = new Set(filteredActualColumns.map((column) => columnFingerprint(metadataColumnContract(column))));
  if (expectedColumnSet.size !== actualColumnSet.size
    || [...expectedColumnSet].some((fingerprint) => !actualColumnSet.has(fingerprint))) {
    throw new Error('Target PostgreSQL column types, nullability, defaults, or identity metadata do not match the canonical manifest.');
  }

  const expectedConstraintSet = new Set(expected.constraints
    .filter(({ tableName }) => includedTables.has(tableName))
    .map(constraintFingerprint));
  const actualConstraintSet = new Set(actualConstraints
    .filter(({ table_name, constraint_type }) => includedTables.has(table_name)
      && (constraint_type === 'PRIMARY KEY' || constraint_type === 'UNIQUE' || constraint_type === 'FOREIGN KEY'))
    .map((constraint) => constraintFingerprint({
      tableName: constraint.table_name,
      constraintType: constraint.constraint_type as TargetConstraintContract['constraintType'],
      columnName: constraint.column_name,
      foreignTableName: constraint.constraint_type === 'FOREIGN KEY'
        ? constraint.foreign_table_name
        : null,
      foreignColumnName: constraint.constraint_type === 'FOREIGN KEY'
        ? constraint.foreign_column_name
        : null,
      deleteRule: constraint.constraint_type === 'FOREIGN KEY'
        ? (constraint.delete_rule ?? 'NO ACTION').toUpperCase()
        : null,
    })));
  if (expectedConstraintSet.size !== actualConstraintSet.size
    || [...expectedConstraintSet].some((fingerprint) => !actualConstraintSet.has(fingerprint))) {
    throw new Error('Target PostgreSQL primary, unique, or foreign-key constraints do not match the canonical manifest.');
  }

  const expectedIndexes = expected.indexes.filter(({ tableName }) => includedTables.has(tableName));
  const expectedIndexNames = new Set(expectedIndexes.map(({ indexName }) => indexName));
  const actualIndexSet = new Set(actualIndexes
    .filter(({ table_name, index_name }) => includedTables.has(table_name)
      && expectedIndexNames.has(index_name))
    .map((index) => indexFingerprint(metadataIndexContract(index))));
  const expectedIndexSet = new Set(expectedIndexes.map(indexFingerprint));
  if (expectedIndexSet.size !== actualIndexSet.size
    || [...expectedIndexSet].some((fingerprint) => !actualIndexSet.has(fingerprint))) {
    throw new Error('Target PostgreSQL indexes do not match the canonical manifest.');
  }
}
